### PR TITLE
Wrote an additional  test (update: and fix) for use base.

### PR DESCRIPTION
**Pull request by exodist**
without my fix, the test fails when 'no circular::require' is in place, but passes normally. My fix which is the second commit in this request solves the problem.

### CODE REVIEW

**Comment by exodist** [comment]
This pull request now contains a fix as well as the test.

**Comment by exodist** [comment]
Added another assertion to the tests for this, 3'rd commit in pull request.

**Comment by doy** [comment]
Thanks. I merged and released the first fix (it was just an oversight when fixing a previous issue), but I really have no interest in getting into special casing all of the different modules out there that might call require on the user's behalf - why doesn't your patch include Class::Load, or Mouse::Util, or Plack::Util, or.... etc.

**Comment by exodist** [comment]
You make a good point. Would you accept the feature if instead of hardcoding base I made it so that you could choose packages to hide at load?

```
no circular::require hide => [qw/ base parent .../];
```

And by default none are hidden?  This avoids the special cases, but still allows for the behavior (which is a useful behavior where I work)

**Comment by doy** [comment]
That sounds reasonable to me.

**Pull request closed without merging**
